### ISSUE TITLE
Confirm bug

### ISSUE THREAD

**Issue by kidynamit** [rehive/rdeploy#1]
**Steps to replicate**
`rdeploy git_release major`

```
Did you remember to commit all changes? ye
Unkown Response. Confirm with y, yes, t, true, on or 1; cancel with n, no, f, false, off or 0.
Did you remember to commit all changes? y
Traceback (most recent call last):
  File "/Users/mwangi/.pyenv/versions/3.6.0/bin/rdeploy", line 11, in <module>
    sys.exit(program.run())
  File "/Users/mwangi/.pyenv/versions/3.6.0/lib/python3.6/site-packages/invoke/program.py", line 285, in run
    self.execute()
  File "/Users/mwangi/.pyenv/versions/3.6.0/lib/python3.6/site-packages/invoke/program.py", line 400, in execute
    executor.execute(*self.tasks)
  File "/Users/mwangi/.pyenv/versions/3.6.0/lib/python3.6/site-packages/invoke/executor.py", line 132, in execute
    result = call.task(*args, **call.kwargs)
  File "/Users/mwangi/.pyenv/versions/3.6.0/lib/python3.6/site-packages/invoke/tasks.py", line 111, in __call__
    result = self.body(*args, **kwargs)
  File "/Users/mwangi/.pyenv/versions/3.6.0/lib/python3.6/site-packages/rdeploy/tasks.py", line 269, in git_release
    confirm('Did you remember to commit all changes? ')
  File "/Users/mwangi/.pyenv/versions/3.6.0/lib/python3.6/site-packages/rdeploy/tasks.py", line 362, in confirm
    if not response_bool:
UnboundLocalError: local variable 'response_bool' referenced before assignment
```

**bug fix** 

Check `feature/confirm-response` branch.

**Comment by kidynamit** [comment]
@michailbrynard can't push to `feature/confirm-response`

**Comment by michailbrynard** [comment]
Sorry, seems there was a permissions issue. You should have access now, thanks!

**Comment by michailbrynard** [comment]
Thanks. I've merged the change. I'll pump the version and push to pypi tomorrow.
