### ISSUE TITLE
Initial git_release issue

### ISSUE THREAD

**Issue by michailbrynard** [rehive/rdeploy#9]
Error running `rdeploy git_release patch` on a repo that doesn't yet have any tags

```Traceback (most recent call last):
  File "/usr/local/miniconda3/envs/general/lib/python3.7/site-packages/rdeploy/tasks.py", line 54, in next_version
    latest_tag = latest_version(ctx)
  File "/usr/local/miniconda3/envs/general/lib/python3.7/site-packages/invoke/tasks.py", line 111, in __call__
    result = self.body(*args, **kwargs)
  File "/usr/local/miniconda3/envs/general/lib/python3.7/site-packages/rdeploy/tasks.py", line 79, in latest_version
    latest_tag = next(version_tags)
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/miniconda3/envs/general/bin/rdeploy", line 11, in <module>
    sys.exit(program.run())
  File "/usr/local/miniconda3/envs/general/lib/python3.7/site-packages/invoke/program.py", line 285, in run
    self.execute()
  File "/usr/local/miniconda3/envs/general/lib/python3.7/site-packages/invoke/program.py", line 400, in execute
    executor.execute(*self.tasks)
  File "/usr/local/miniconda3/envs/general/lib/python3.7/site-packages/invoke/executor.py", line 132, in execute
    result = call.task(*args, **call.kwargs)
  File "/usr/local/miniconda3/envs/general/lib/python3.7/site-packages/invoke/tasks.py", line 111, in __call__
    result = self.body(*args, **kwargs)
  File "/usr/local/miniconda3/envs/general/lib/python3.7/site-packages/rdeploy/tasks.py", line 271, in git_release
    bumped_version = next_version(ctx, bump=version_bump)
  File "/usr/local/miniconda3/envs/general/lib/python3.7/site-packages/invoke/tasks.py", line 111, in __call__
    result = self.body(*args, **kwargs)
  File "/usr/local/miniconda3/envs/general/lib/python3.7/site-packages/rdeploy/tasks.py", line 55, in next_version
    except ReleaseError:
TypeError: catching classes that do not inherit from BaseException is not allowed```

**Comment by kidynamit** [comment]
Fixed with version 0.0.15
